version: "3.9"

services:
    postgres:
        image: postgres:15
        container_name: postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

    app:
        build: .
        container_name: wb-tariff-service
        restart: always
        env_file:
            - .env
        depends_on:
            - postgres
        volumes:
            - .:/app

volumes:
    pgdata:
